name: Future
options:
  bundleIdPrefix: com.shopgun
  deploymentTarget:
    iOS: 8.0
    macOS: '10.10'
    watchOS: 2.0
targets:
  Future:
    platform: [iOS, macOS, watchOS]
    scheme:
      gatherCoverageData: true
      testTargets: ['FutureTests_${platform}']
    templates: 
      - Framework

  FutureTests:
    platform: [iOS, macOS, watchOS]
    type: bundle.unit-test
    settings:
      SWIFT_VERSION: 5.0
    dependencies: [{target: 'Future_${platform}'}]
    sources:
      - path: Tests

targetTemplates:
  Framework:
    type: framework
    settings:
      SWIFT_VERSION: 5.0
    sources: 
      - path: Sources
